### ISSUE TITLE
HrefMiddleware seems to break FastAPI lifespan context

### ISSUE THREAD

**Issue by NodeJSmith** [jasujm/hrefs#9]
When I add the HrefMiddleware to my application, my lifespan async context manager no longer gets called. I assume the project works with the startup/shutdown events, though I haven't tried it.

Is there support for the lifespan context? Perhaps I am doing something wrong when configuring this.

**Comment by jasujm** [comment]
The library was originally written for a project that didn't use lifespans, so I've simply never tested it. I'd like to support them, so will investigate. Chances are the middleware isn't general enough.

**Comment by jasujm** [comment]
@NodeJSmith thank you for reporting this. The problem was in the middleware implementation. It's now fixed in 0.11
